POST localhost:8080/api/v1/applications
Content-Type: application/json

{
  "email": "myemail@gmail.com",
  "name": "DenisV",
  "githubUser": "DenisVabishchevich",
  "projects": [
    {
      "name": "Super Project",
      "employmentMode": "EMPLOYED",
      "capacity": "FULL_TIME",
      "duration": "PT840H",
      "startYear": 2022,
      "role": "Software Developer",
      "teamSize": 10,
      "repositoryUrl": "www.repo-url.com",
      "lifeUrl": "www.life.com"
    }
  ]
}
