create table application
(
    id          bigint generated by default as identity,
    created     timestamp,
    created_by  varchar(255),
    updated     timestamp,
    updated_by  varchar(255),
    e_mail      varchar(255),
    github_user varchar(255),
    name        varchar(255),
    primary key (id)
);

create table past_project
(
    id              bigint generated by default as identity,
    created         timestamp,
    created_by      varchar(255),
    updated         timestamp,
    updated_by      varchar(255),
    capacity        varchar(255),
    duration        bigint,
    employment_mode varchar(255),
    life_url        varchar(255),
    name            varchar(255),
    repository_url  varchar(255),
    role            varchar(255),
    start_year      integer,
    team_size       integer,
    application_id  bigint,
    primary key (id)
);

alter table past_project
    add constraint past_project_application_fk foreign key (application_id) references application