CREATE TABLE application
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email       VARCHAR(255)                                        NOT NULL,
    github_user VARCHAR(255)                                        NOT NULL,
    name        VARCHAR(255)                                        NOT NULL,
    created     TIMESTAMP                                           NOT NULL,
    created_by  VARCHAR(255),
    updated     TIMESTAMP                                           NOT NULL,
    updated_by  VARCHAR(255),
    UNIQUE (name, email)

);

CREATE TABLE past_project
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    capacity        VARCHAR(255)                                        NOT NULL,
    duration        BIGINT                                              NOT NULL,
    employment_mode VARCHAR(255)                                        NOT NULL,
    name            VARCHAR(255)                                        NOT NULL,
    role            VARCHAR(255)                                        NOT NULL,
    start_year      INTEGER                                             NOT NULL,
    team_size       INTEGER                                             NOT NULL,
    application_id  BIGINT                                              NOT NULL,
    repository_url  VARCHAR(255),
    life_url        VARCHAR(255),
    created         TIMESTAMP                                           NOT NULL,
    created_by      VARCHAR(255),
    updated         TIMESTAMP                                           NOT NULL,
    updated_by      VARCHAR(255)
);

ALTER TABLE past_project
    ADD CONSTRAINT past_project_application_fk FOREIGN KEY (application_id) REFERENCES application